name: climate_similarity_measures
channels:
  - conda-forge
  - defaults
dependencies:
  - basemap
  - seaborn
  - jupyter
  - python=3.6
  - joblib
  - minepy
  - pip
  - pip:
    - pyinform
    - sklearn
    - similaritymeasures
    - scikit-image
